[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyweste"
version = "0.0.1"
license = { text = "MIT" }
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["pyweste"]
